[package]
name = "tig-syntax"
version = "0.1.0"
edition = "2021"
authors = ["Erick Hernandez Curiel <erick@hernandezcuriel.dev>"]

[dependencies]
smol_str = "0.1"
tig-common = { path = "../tig-common" }
